"""empty message

Revision ID: 9872e4a3e470
Revises: aa47bdf2f4e0
Create Date: 2016-03-30 16:17:23.218255

"""

# revision identifiers, used by Alembic.
revision = '9872e4a3e470'
down_revision = 'aa47bdf2f4e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('http_request_log', sa.Column('operation', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('http_request_log', 'operation')
    ### end Alembic commands ###
