"""empty message

Revision ID: aa47bdf2f4e0
Revises: None
Create Date: 2016-03-30 16:02:08.276024

"""

# revision identifiers, used by Alembic.
revision = 'aa47bdf2f4e0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('http_request_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_time', sa.DateTime(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('forwarded_for', sa.String(), nullable=True),
    sa.Column('originating_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_http_request_log_access_time'), 'http_request_log', ['access_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_http_request_log_access_time'), table_name='http_request_log')
    op.drop_table('http_request_log')
    ### end Alembic commands ###
